#!/usr/bin/env python3
"""Regenerate the versioned dead-package snapshots from the curated manifest.

The offline snapshot is *data, not code*: maintainers edit
``scripts/deprecation-sources.yaml``, then this script re-renders both
JSON copies (``data/`` repo-level and ``src/lang_fossil/data/`` packaged) so
they never drift. Runtime code stays offline-first and only reads JSON.

Usage (from the repository root):

    python scripts/sync_deprecations.py check    # snapshots == manifest (no network)
    python scripts/sync_deprecations.py verify   # fetch each ref_url, assert tokens
    python scripts/sync_deprecations.py write    # regenerate both copies (+version bump)
    python scripts/sync_deprecations.py write --version 2026.09

Security: entries are loaded with ``yaml.safe_load``; refs are fetched with
urllib against URLs explicitly declared in the manifest (read-only).
"""

from __future__ import annotations

import argparse
import json
import sys
import urllib.request
from datetime import date
from pathlib import Path
from typing import Any

import yaml

_ROOT = Path(__file__).resolve().parent.parent
_MANIFEST = Path(__file__).resolve().parent / "deprecation-sources.yaml"
_SNAPSHOT_NAME = "dead-packages.json"
_ENTRY_KEYS = ("module", "attribute", "removed_in", "removal", "replacement")
_GENERATED_NOTE = (
    "Generated by scripts/sync_deprecations.py from "
    "scripts/deprecation-sources.yaml; do not edit by hand."
)


def load_manifest(path: Path = _MANIFEST) -> dict[str, Any]:
    """Load and validate the curated manifest.

    Args:
        path: Path to ``deprecation-sources.yaml``.

    Returns:
        The parsed manifest mapping.

    Raises:
        ValueError: If the file is missing, not a mapping, or lacks the
            ``packages`` list.
    """
    try:
        raw = yaml.safe_load(path.read_text(encoding="utf-8"))
    except yaml.YAMLError as exc:
        raise ValueError(f"invalid manifest {path}: {exc}") from exc
    if not isinstance(raw, dict) or not isinstance(raw.get("packages"), list):
        raise ValueError(f"{path} must be a mapping with a 'packages' list")
    return raw


def render_document(manifest: dict[str, Any], version: str) -> dict[str, Any]:
    """Render the JSON snapshot document for a manifest and version.

    Args:
        manifest: Parsed manifest.
        version: Snapshot version stamp (e.g. ``2026.09``).

    Returns:
        The JSON-serializable snapshot document.
    """
    packages: list[dict[str, Any]] = []
    for index, entry in enumerate(manifest["packages"]):
        if not isinstance(entry, dict) or not isinstance(entry.get("module"), str):
            raise ValueError(f"packages#{index}: every entry needs a string 'module'")
        packages.append({key: entry[key] for key in _ENTRY_KEYS if key in entry})
    return {
        "$comment": _GENERATED_NOTE,
        "schema_version": int(manifest.get("schema_version", 1)),
        "snapshot_version": version,
        "sources": [dict(source) for source in manifest.get("sources", [])],
        "packages": packages,
    }


def _snapshot_signature(snapshot: dict[str, Any]) -> dict[str, Any]:
    """Return the comparison-relevant part of a snapshot (ignore version).

    Args:
        snapshot: A loaded snapshot document.

    Returns:
        The document with ``snapshot_version`` removed.
    """
    return {key: value for key, value in snapshot.items() if key != "snapshot_version"}


def check(root: Path = _ROOT, version: str = "") -> bool:
    """Verify both snapshot copies match the manifest.

    Args:
        root: Repository root.
        version: Expected version stamp (empty = the stamp already on disk is
            accepted as long as content matches).

    Returns:
        True when both copies are in sync with the manifest.
    """
    manifest = load_manifest(root / "scripts" / "deprecation-sources.yaml")
    expected = render_document(manifest, version or date.today().strftime("%Y.%m"))
    ok = True
    for path in _copies_for(root):
        if not path.is_file():
            print(f"[missing] {path}")
            ok = False
            continue
        try:
            current = json.loads(path.read_text(encoding="utf-8"))
        except (OSError, ValueError) as exc:
            print(f"[invalid] {path}: {exc}")
            ok = False
            continue
        if _snapshot_signature(current) == _snapshot_signature(expected):
            print(f"[ok] {path}")
        else:
            print(f"[out of sync] {path}: re-run `write` after manifest edits")
            ok = False
    return ok


def verify(root: Path = _ROOT, timeout: float = 15.0) -> bool:
    """Fetch each declared ``ref_url`` and assert its tokens appear.

    Args:
        root: Repository root.
        timeout: Per-fetch timeout in seconds.

    Returns:
        True when every entry with a ``ref_url`` is corroborated by the
        referenced page (entries without a ref are skipped with a notice).
    """
    manifest = load_manifest(root / "scripts" / "deprecation-sources.yaml")
    ok = True
    checked = 0
    for entry in manifest["packages"]:
        if not isinstance(entry, dict):
            continue
        ref = entry.get("ref_url")
        if not isinstance(ref, str) or not ref:
            print(f"[skipped] {entry.get('module')}: no ref_url declared")
            continue
        try:
            text = _fetch_text(ref, timeout)
        except OSError as exc:
            print(f"[fetch error] {ref}: {exc}")
            ok = False
            continue
        tokens = [entry["module"]] + ([entry["attribute"]] if entry.get("attribute") else [])
        missing = [token for token in tokens if token not in text]
        checked += 1
        if missing:
            print(f"[missing tokens] {ref}: {missing}")
            ok = False
        else:
            print(f"[ok] {ref}: {tokens}")
    print(f"refs checked: {checked}")
    return ok


def write(root: Path = _ROOT, version: str | None = None) -> None:
    """Regenerate both snapshot copies from the manifest.

    Args:
        root: Repository root.
        version: Version stamp; defaults to today's ``YYYY.MM``.
    """
    manifest = load_manifest(root / "scripts" / "deprecation-sources.yaml")
    stamp = version or date.today().strftime("%Y.%m")
    document = render_document(manifest, stamp)
    payload = json.dumps(document, indent=2, ensure_ascii=False) + "\n"
    for path in _copies_for(root):
        path.write_text(payload, encoding="utf-8")
        print(f"[written] {path} (snapshot_version={stamp})")


def _copies_for(root: Path) -> tuple[Path, Path]:
    """Return the two snapshot destinations under a repository root.

    Args:
        root: Repository root.

    Returns:
        The (repo-level, packaged) snapshot paths.
    """
    return (
        root / "data" / _SNAPSHOT_NAME,
        root / "src" / "lang_fossil" / "data" / _SNAPSHOT_NAME,
    )


def _fetch_text(url: str, timeout: float) -> str:
    """Fetch a URL body as text (http/https) or read a local file path.

    Args:
        url: ``http(s)`` URL or an existing local file path (tests).
        timeout: Network timeout in seconds.

    Returns:
        The fetched text.

    Raises:
        OSError: When the fetch or read fails.
    """
    if url.startswith(("http://", "https://")):
        with urllib.request.urlopen(url, timeout=timeout) as response:  # noqa: S310
            return response.read().decode("utf-8", errors="replace")
    path = Path(url)
    if path.is_file():
        return path.read_text(encoding="utf-8", errors="replace")
    raise FileNotFoundError(url)


def _parse_args(argv: list[str] | None = None) -> argparse.Namespace:
    """Parse command-line arguments."""
    parser = argparse.ArgumentParser(
        description="Regenerate dead-package snapshots from the curated manifest."
    )
    parser.add_argument("command", choices=("check", "verify", "write"))
    parser.add_argument("--version", help="Snapshot version stamp for `write`.")
    parser.add_argument(
        "--root",
        type=Path,
        default=_ROOT,
        help="Repository root (defaults to the script's parent).",
    )
    return parser.parse_args(argv)


def main(argv: list[str] | None = None) -> int:
    """Run the requested command; returns a process exit code."""
    args = _parse_args(argv)
    try:
        if args.command == "check":
            return 0 if check(args.root) else 1
        if args.command == "verify":
            return 0 if verify(args.root) else 1
        write(args.root, version=args.version)
        return 0
    except ValueError as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 2


if __name__ == "__main__":
    raise SystemExit(main())
